Added JSON schema for randomisers
ieahleen/habitican-randomizer pull request #58
Opened 2022-10-07 14:41 UTC by aswinikalyan30

Closes #49

2022-10-07 15:17 UTC, ieahleen commented
can you add an .md file in there that describe at what api call each file correspond?

2022-10-07 16:13 UTC, aswinikalyan30 commented
Sure!

2022-10-08 04:25 UTC, aswinikalyan30 commented
Added the description too!

2022-10-08 16:55 UTC, ieahleen requested changes
Thank you, I suggested a few changes to the `.md` file

2022-10-08 16:55 UTC, ieahleen commented on json_files/jsonFiles.md
> +The API call it responds to is: ```https://habitica.com/api/v3/user/equip/pet/{pet_name}```
```suggestion
* Equip [Random Pet](equipPet.json) : This JSON file contains the schema for equpping a random pet from habitica. 

The API call it responds to is: `https://habitica.com/api/v3/user/equip/pet/{pet_name}`
```

2022-10-08 16:55 UTC, ieahleen commented on json_files/jsonFiles.md
> +The API call it responds to is : ``` https://habitica.com/api/v3/user/unlock?path=background.{color} ```
```suggestion
* Equip [Random Background](equipBGcolor.json) :  This JSON file contains the schema for equipping a random backgroundd from habitica

The API call it responds to is : `https://habitica.com/api/v3/user/unlock?path=background.{color}`
```

2022-10-08 16:55 UTC, ieahleen commented on json_files/jsonFiles.md
> +The API call it responds to is: ```https://habitica.com/api/v3/user/buy-gear/{itemToPurchase.key}```
```suggestion
* [Buy New Equpiment](buyNewEquip.json) : This JSON file contains the schema for buying a new quipment from the market in habitica. 

The API call it responds to is: `https://habitica.com/api/v3/user/buy-gear/{itemToPurchase.key}`
```

2022-10-08 16:55 UTC, ieahleen commented on json_files/jsonFiles.md
> +The API call it responds to is : ``` https://habitica.com/api/v3/user/equip/costume/{costume_name} ```
```suggestion
* Equip [Random Costume](costumeRandom.json) :  This JSON file contains the schema for equipping a random piece of equipment ascostume from habitica

The API call it responds to is : `https://habitica.com/api/v3/user/equip/costume/{costume_name}` 
```

2022-10-08 16:55 UTC, ieahleen commented on json_files/jsonFiles.md
> +The API call it responds to is : ``` https://habitica.com/api/v3/user/equip/equipped/{item} ```
```suggestion
[Random Battle Gear](battlegearRndm.json) : This JSON file contains the schema for equipping a randompiece of equipment as battle gear from habitica

The API call it responds to is : `https://habitica.com/api/v3/user/equip/equipped/{item}`
```

2022-10-08 17:14 UTC, aswinikalyan30 commented
Updated them :)

2022-10-08 17:24 UTC, ieahleen requested changes
I think it's missing the user data API call and the Habitica content API call, if you please can add those too

Also this doesn't close #49, it's not related at all to #49, please change what issue you are referring to

2022-10-08 17:31 UTC, aswinikalyan30 commented
So which issue is this related to?

2022-10-08 17:32 UTC, aswinikalyan30 commented
#49 is the one for json schema

2022-10-08 17:38 UTC, ieahleen commented
json schema of the tool, you are doing #36

2022-10-10 07:56 UTC, aswinikalyan30 commented
Updated with relevant changes

2022-10-17 10:49 UTC, ieahleen commented on json_files/jsonFiles.md
> +The API call it responds to is: `https://habitica.com/api/v3/user/equip/pet/{pet_name}`
```suggestion
* Equip [Random Pet](equipPet.json) is the response to `https://habitica.com/api/v3/user/equip/pet/{pet_name}`

This is the API endpoint to equip a new pet
```

2022-10-17 10:49 UTC, ieahleen commented on json_files/jsonFiles.md
> +The API call it responds to is : ` https://habitica.com/api/v3/user/unlock?path=background.{color} `
```suggestion
* Equip [Random Background](equipBGcolor.json) is the response to `https://habitica.com/api/v3/user/unlock?path=background.{color}`

This is the call to equip a background.
```

2022-10-17 10:50 UTC, ieahleen commented on json_files/jsonFiles.md
> +The API call it responds to is: `https://habitica.com/api/v3/user/buy-gear/{itemToPurchase.key}`
```suggestion
* [Buy New Equpiment](buyNewEquip.json) is the response to `https://habitica.com/api/v3/user/buy-gear/{itemToPurchase.key}`

This is the API endpoint to buy a piece of gear.
```

2022-10-17 10:51 UTC, ieahleen commented on json_files/jsonFiles.md
> +The API call it responds to is : ` https://habitica.com/api/v3/user/equip/costume/{costume_name} `
```suggestion
* Equip [Random Costume](costumeRandom.json) is the response to `https://habitica.com/api/v3/user/equip/costume/{costume_name}`

It's the API endpoint to equip a piece of gear as costume
```

2022-10-17 10:51 UTC, ieahleen commented on json_files/jsonFiles.md
> +The API call it responds to is : ` https://habitica.com/api/v3/user/equip/equipped/{item} `
```suggestion
* [Random Battle Gear](battlegearRndm.json) is the response to `https://habitica.com/api/v3/user/equip/equipped/{item}`

Same as above but for battle gear
```

2022-10-17 10:52 UTC, ieahleen commented on json_files/jsonFiles.md
> +The API call it responds to is : ` https://habitica.com/api/v3/user `
```suggestion
* [User](user.json) is the response to `https://habitica.com/api/v3/user`

This is the API call to get all the user data
```

2022-10-17 10:54 UTC, ieahleen commented on json_files/jsonFiles.md
> +The API call it responds to is : ` https://habitica.com/api/v3/content?language=en `
```suggestion
* [Content](content.json) is the response to `https://habitica.com/api/v3/content?language=en`

It's all available Habitica content.
```

2022-10-17 11:17 UTC, aswinikalyan30 commented
Done!

2022-10-17 11:52 UTC, merged